/*
 * mgl_kernels_msl.h
 * MGL
 *
 * Copyright (c) 2015-2026 The Brenwill Workshop Ltd. (http://www.brenwill.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Modified by The MooGL Project for MGL: taken from MoltenVK's
 * MVKCommandPipelineStateFactoryShaderSource.h. Vulkan-specific types and the
 * blit/clear/resolve/tessellation kernels were removed; the multiview
 * (viewCount) parameters were dropped; restart-index remap kernels and
 * standalone triangle-fan kernels were added.
 */

#ifndef mgl_kernels_msl_h
#define mgl_kernels_msl_h

static const char *const mgl_kernels_msl_source =
"#include <metal_stdlib>\n"
"using namespace metal;\n"
"\n"
"typedef struct {\n"
"    uint32_t srcOffset;\n"
"    uint32_t dstOffset;\n"
"    uint32_t size;\n"
"} CopyInfo;\n"
"\n"
"typedef enum : uint8_t {\n"
"    MTLIndexTypeUInt16 = 0,\n"
"    MTLIndexTypeUInt32 = 1,\n"
"} MTLIndexType;\n"
"\n"
"typedef struct MGLVtxAdj {\n"
"    MTLIndexType idxType;\n"
"    bool isTriFan;\n"
"    bool isPrimRestart;\n"
"    bool isUint8Index;\n"
"    bool isProvokingVertexLast;\n"
"} MGLVtxAdj;\n"
"\n"
"// Populates triangle vertex indexes for a triangle fan.\n"
"template<typename T>\n"
"static inline void populateTriIndxsFromTriFan(device T* triIdxs,\n"
"                                              constant T* triFanIdxs,\n"
"                                              uint32_t triFanIdxCnt,\n"
"                                              constant MGLVtxAdj& vtxAdj) {\n"
"    T primRestartSentinel = vtxAdj.isUint8Index ? (T)0xFF : (T)0xFFFFFFFF;\n"
"    uint32_t triIdxIdx = 0;\n"
"    uint32_t triFanBaseIdx = 0;\n"
"    uint32_t triFanIdxIdx = triFanBaseIdx + 2;\n"
"    while (triFanIdxIdx < triFanIdxCnt) {\n"
"        uint32_t triFanBaseIdxCurr = triFanBaseIdx;\n"
"\n"
"        // Detect primitive restart on any index, to catch possible consecutive restarts\n"
"        T triIdx0 = triFanIdxs[triFanBaseIdx];\n"
"        if (vtxAdj.isPrimRestart && triIdx0 == primRestartSentinel)\n"
"            triFanBaseIdx++;\n"
"\n"
"        T triIdx1 = triFanIdxs[triFanIdxIdx - 1];\n"
"        if (vtxAdj.isPrimRestart && triIdx1 == primRestartSentinel)\n"
"            triFanBaseIdx = triFanIdxIdx;\n"
"\n"
"        T triIdx2 = triFanIdxs[triFanIdxIdx];\n"
"        if (vtxAdj.isPrimRestart && triIdx2 == primRestartSentinel)\n"
"            triFanBaseIdx = triFanIdxIdx + 1;\n"
"\n"
"        if (triFanBaseIdx != triFanBaseIdxCurr) {    // Restart the triangle fan\n"
"            triFanIdxIdx = triFanBaseIdx + 2;\n"
"        } else {\n"
"            // Provoking vertex is 1 in triangle fan but 0 in triangle list\n"
"            triIdxs[triIdxIdx++] = vtxAdj.isProvokingVertexLast ? triIdx0 : triIdx1;\n"
"            triIdxs[triIdxIdx++] = vtxAdj.isProvokingVertexLast ? triIdx1 : triIdx2;\n"
"            triIdxs[triIdxIdx++] = vtxAdj.isProvokingVertexLast ? triIdx2 : triIdx0;\n"
"            triFanIdxIdx++;\n"
"        }\n"
"    }\n"
"}\n"
"\n"
"kernel void cmdCopyBufferBytes(device uint8_t* src [[ buffer(0) ]],\n"
"                               device uint8_t* dst [[ buffer(1) ]],\n"
"                               constant CopyInfo& info [[ buffer(2) ]]) {\n"
"    for (size_t i = 0; i < info.size; i++) {\n"
"        dst[i + info.dstOffset] = src[i + info.srcOffset];\n"
"    }\n"
"}\n"
"\n"
"kernel void cmdFillBuffer(device uint32_t* dst [[ buffer(0) ]],\n"
"                          constant uint32_t& fillValue [[ buffer(1) ]],\n"
"                          uint pos [[thread_position_in_grid]]) {\n"
"    dst[pos] = fillValue;\n"
"}\n"
"\n"
"kernel void convertUint8Indices(device uint8_t* src [[ buffer(0) ]],\n"
"                                device uint16_t* dst [[ buffer(1) ]],\n"
"                                uint pos [[thread_position_in_grid]]) {\n"
"    uint8_t idx = src[pos];\n"
"    dst[pos] = idx == 0xFF ? 0xFFFF : idx;\n"
"}\n"
"\n"
"kernel void convertUint8IndicesRaw(device uint8_t* src [[ buffer(0) ]],\n"
"                                   device uint16_t* dst [[ buffer(1) ]],\n"
"                                   uint pos [[thread_position_in_grid]]) {\n"
"    uint8_t idx = src[pos];\n"
"    dst[pos] = idx;\n"
"}\n"
"\n"
"kernel void cmdDrawIndexedCopyIndex16Buffer(const device uint16_t* srcBuff [[buffer(0)]],\n"
"                                            device uint16_t* destBuff [[buffer(1)]],\n"
"                                            const device MTLDrawIndexedPrimitivesIndirectArguments& params [[buffer(2)]],\n"
"                                            uint i [[thread_position_in_grid]]) {\n"
"    destBuff[i] = srcBuff[params.indexStart + i];\n"
"}\n"
"\n"
"kernel void cmdDrawIndexedCopyIndex32Buffer(const device uint32_t* srcBuff [[buffer(0)]],\n"
"                                            device uint32_t* destBuff [[buffer(1)]],\n"
"                                            const device MTLDrawIndexedPrimitivesIndirectArguments& params [[buffer(2)]],\n"
"                                            uint i [[thread_position_in_grid]]) {\n"
"    destBuff[i] = srcBuff[params.indexStart + i];\n"
"}\n"
"\n"
"kernel void cmdDrawIndirectPopulateIndexes(const device char* srcBuff [[buffer(0)]],\n"
"                                           device MTLDrawIndexedPrimitivesIndirectArguments* destBuff [[buffer(1)]],\n"
"                                           constant uint32_t& srcStride [[buffer(2)]],\n"
"                                           constant uint32_t& drawCount [[buffer(3)]],\n"
"                                           device uint32_t* idxBuff [[buffer(4)]],\n"
"                                           uint idx [[thread_position_in_grid]]) {\n"
"    if (idx >= drawCount) { return; }\n"
"    const device auto& src = *reinterpret_cast<const device MTLDrawPrimitivesIndirectArguments*>(srcBuff + idx * srcStride);\n"
"    device auto& dst = destBuff[idx];\n"
"    dst.indexCount = src.vertexCount;\n"
"    dst.indexStart = src.vertexStart;\n"
"    dst.baseVertex = 0;\n"
"    dst.instanceCount = src.instanceCount;\n"
"    dst.baseInstance = src.baseInstance;\n"
"\n"
"    for (uint32_t idxIdx = 0; idxIdx < dst.indexCount; idxIdx++) {\n"
"        uint32_t idxBuffIdx = dst.indexStart + idxIdx;\n"
"        idxBuff[idxBuffIdx] = idxBuffIdx;\n"
"    }\n"
"}\n"
"\n"
"kernel void cmdDrawIndirectConvertBuffers(const device char* srcBuff [[buffer(0)]],\n"
"                                          device MTLDrawPrimitivesIndirectArguments* destBuff [[buffer(1)]],\n"
"                                          constant uint32_t& srcStride [[buffer(2)]],\n"
"                                          constant uint32_t& drawCount [[buffer(3)]],\n"
"                                          uint idx [[thread_position_in_grid]]) {\n"
"    if (idx >= drawCount) { return; }\n"
"    const device auto& src = *reinterpret_cast<const device MTLDrawPrimitivesIndirectArguments*>(srcBuff + idx * srcStride);\n"
"    destBuff[idx] = src;\n"
"}\n"
"\n"
"kernel void cmdDrawIndirectCountConvertBuffers(const device char* srcBuff [[buffer(0)]],\n"
"                                               device MTLDrawPrimitivesIndirectArguments* destBuff [[buffer(1)]],\n"
"                                               constant uint32_t& srcStride [[buffer(2)]],\n"
"                                               constant uint32_t& drawCount [[buffer(3)]],\n"
"                                               const device uint32_t* countBuff [[buffer(4)]],\n"
"                                               uint idx [[thread_position_in_grid]]) {\n"
"    if (idx >= drawCount) { return; }\n"
"    const device auto& src = *reinterpret_cast<const device MTLDrawPrimitivesIndirectArguments*>(srcBuff + idx * srcStride);\n"
"    destBuff[idx] = src;\n"
"    if (idx >= countBuff[0]) {\n"
"        destBuff[idx].instanceCount = 0;\n"
"    }\n"
"}\n"
"\n"
"kernel void cmdDrawIndexedIndirectConvertBuffers(const device char* srcBuff [[buffer(0)]],\n"
"                                                 device MTLDrawIndexedPrimitivesIndirectArguments* destBuff [[buffer(1)]],\n"
"                                                 constant uint32_t& srcStride [[buffer(2)]],\n"
"                                                 constant uint32_t& drawCount [[buffer(3)]],\n"
"                                                 constant MGLVtxAdj& vtxAdj [[buffer(4)]],\n"
"                                                 device void* triIdxs [[buffer(5)]],\n"
"                                                 constant void* triFanIdxs [[buffer(6)]],\n"
"                                                 uint idx [[thread_position_in_grid]]) {\n"
"    if (idx >= drawCount) { return; }\n"
"    const device auto& src = *reinterpret_cast<const device MTLDrawIndexedPrimitivesIndirectArguments*>(srcBuff + idx * srcStride);\n"
"    destBuff[idx] = src;\n"
"\n"
"    device auto& dst = destBuff[idx];\n"
"    if (vtxAdj.isTriFan) {\n"
"        dst.indexCount = (src.indexCount - 2) * 3;\n"
"        switch (vtxAdj.idxType) {\n"
"            case MTLIndexTypeUInt16:\n"
"                populateTriIndxsFromTriFan(&((device uint16_t*)triIdxs)[dst.indexStart],\n"
"                                           &((constant uint16_t*)triFanIdxs)[src.indexStart],\n"
"                                           src.indexCount,\n"
"                                           vtxAdj);\n"
"                break;\n"
"            case MTLIndexTypeUInt32:\n"
"                populateTriIndxsFromTriFan(&((device uint32_t*)triIdxs)[dst.indexStart],\n"
"                                           &((constant uint32_t*)triFanIdxs)[src.indexStart],\n"
"                                           src.indexCount,\n"
"                                           vtxAdj);\n"
"                break;\n"
"        }\n"
"    }\n"
"}\n"
"\n"
"kernel void cmdDrawIndexedIndirectCountConvertBuffers(const device char* srcBuff [[buffer(0)]],\n"
"                                                      device MTLDrawIndexedPrimitivesIndirectArguments* destBuff [[buffer(1)]],\n"
"                                                      constant uint32_t& srcStride [[buffer(2)]],\n"
"                                                      constant uint32_t& drawCount [[buffer(3)]],\n"
"                                                      const device uint32_t* countBuff [[buffer(4)]],\n"
"                                                      uint idx [[thread_position_in_grid]]) {\n"
"    if (idx >= drawCount) { return; }\n"
"    const device auto& src = *reinterpret_cast<const device MTLDrawIndexedPrimitivesIndirectArguments*>(srcBuff + idx * srcStride);\n"
"    destBuff[idx] = src;\n"
"    if (idx >= countBuff[0]) {\n"
"        destBuff[idx].instanceCount = 0;\n"
"    }\n"
"}\n"
"\n"
"typedef struct alignas(8) {\n"
"    uint32_t count;\n"
"    uint32_t countHigh;\n"
"} VisibilityBuffer;\n"
"\n"
"typedef struct alignas(8) {\n"
"    atomic_uint count;\n"
"    atomic_uint countHigh;\n"
"} AtomicVisibilityBuffer;\n"
"\n"
"typedef struct alignas(8) {\n"
"    uint32_t dst;\n"
"    uint32_t src;\n"
"} QueryResultOffsets;\n"
"\n"
"typedef enum {\n"
"    Initial,\n"
"    DeviceAvailable,\n"
"    Available\n"
"} QueryStatus;\n"
"\n"
"typedef enum {\n"
"    MGL_QUERY_RESULT_64_BIT                = 0x00000001,\n"
"    MGL_QUERY_RESULT_WAIT_BIT              = 0x00000002,\n"
"    MGL_QUERY_RESULT_WITH_AVAILABILITY_BIT = 0x00000004,\n"
"    MGL_QUERY_RESULT_PARTIAL_BIT           = 0x00000008,\n"
"} MGLQueryResultFlagBits;\n"
"\n"
"kernel void cmdCopyQueryPoolResultsToBuffer(const device VisibilityBuffer* src [[buffer(0)]],\n"
"                                            device uint8_t* dest [[buffer(1)]],\n"
"                                            constant uint& stride [[buffer(2)]],\n"
"                                            constant uint& numQueries [[buffer(3)]],\n"
"                                            constant uint& flags [[buffer(4)]],\n"
"                                            constant QueryStatus* availability [[buffer(5)]],\n"
"                                            uint query [[thread_position_in_grid]]) {\n"
"    if (query >= numQueries) { return; }\n"
"    device uint32_t* destCount = (device uint32_t*)(dest + stride * query);\n"
"    if (availability[query] != Initial || flags & MGL_QUERY_RESULT_PARTIAL_BIT) {\n"
"        destCount[0] = src[query].count;\n"
"        if (flags & MGL_QUERY_RESULT_64_BIT) { destCount[1] = src[query].countHigh; }\n"
"    }\n"
"    if (flags & MGL_QUERY_RESULT_WITH_AVAILABILITY_BIT) {\n"
"        if (flags & MGL_QUERY_RESULT_64_BIT) {\n"
"            destCount[2] = availability[query] != Initial ? 1 : 0;\n"
"            destCount[3] = 0;\n"
"        } else {\n"
"            destCount[1] = availability[query] != Initial ? 1 : 0;\n"
"        }\n"
"    }\n"
"}\n"
"\n"
"kernel void accumulateOcclusionQueryResults(uint pos [[thread_position_in_grid]],\n"
"                                            const device QueryResultOffsets* offsets  [[buffer(0)]],\n"
"                                            device AtomicVisibilityBuffer* dst_buffer [[buffer(1)]],\n"
"                                            const device VisibilityBuffer* src_buffer [[buffer(2)]]) {\n"
"    VisibilityBuffer src = src_buffer[offsets[pos].src];\n"
"    device AtomicVisibilityBuffer& dst = dst_buffer[offsets[pos].dst];\n"
"    uint32_t prev_lo = atomic_fetch_add_explicit(&dst.count, src.count, memory_order_relaxed);\n"
"    uint32_t next_lo = prev_lo + src.count;\n"
"    atomic_fetch_add_explicit(&dst.countHigh, src.countHigh, memory_order_relaxed);\n"
"    if (next_lo < prev_lo)\n"
"        atomic_fetch_add_explicit(&dst.countHigh, 1, memory_order_relaxed);\n"
"}\n"
"\n"
"kernel void triFanIndexes16(constant uint16_t* fanIdxs [[buffer(0)]],\n"
"                             device uint16_t* triIdxs [[buffer(1)]],\n"
"                             constant uint32_t& fanIdxCount [[buffer(2)]],\n"
"                             constant MGLVtxAdj& vtxAdj [[buffer(3)]],\n"
"                             uint tid [[thread_position_in_grid]]) {\n"
"    if (tid != 0) return;\n"
"    populateTriIndxsFromTriFan(triIdxs, fanIdxs, fanIdxCount, vtxAdj);\n"
"}\n"
"\n"
"kernel void triFanIndexes32(constant uint32_t* fanIdxs [[buffer(0)]],\n"
"                             device uint32_t* triIdxs [[buffer(1)]],\n"
"                             constant uint32_t& fanIdxCount [[buffer(2)]],\n"
"                             constant MGLVtxAdj& vtxAdj [[buffer(3)]],\n"
"                             uint tid [[thread_position_in_grid]]) {\n"
"    if (tid != 0) return;\n"
"    populateTriIndxsFromTriFan(triIdxs, fanIdxs, fanIdxCount, vtxAdj);\n"
"}\n"
"\n"
"kernel void remapRestartIndex16(device uint16_t* idx [[buffer(0)]],\n"
"                                 constant uint32_t& glRestartIndex [[buffer(1)]],\n"
"                                 uint pos [[thread_position_in_grid]]) {\n"
"    if (idx[pos] == (uint16_t)glRestartIndex) idx[pos] = (uint16_t)~0;\n"
"}\n"
"\n"
"kernel void remapRestartIndex32(device uint32_t* idx [[buffer(0)]],\n"
"                                 constant uint32_t& glRestartIndex [[buffer(1)]],\n"
"                                 uint pos [[thread_position_in_grid]]) {\n"
"    if (idx[pos] == glRestartIndex) idx[pos] = ~0u;\n"
"}\n"
;

#endif /* mgl_kernels_msl_h */
