//
// Autogenerated from gl.xml
//
// Mike Larson
//
// October 2021
//

#include <assert.h>

#include "mgl.h"
#include "mgl_log.h"
#include "mgl_format_table.h"

extern Renderbuffer *findRenderbuffer(GLMContext ctx, GLuint renderbuffer);

// Forward declarations for transform feedback functions from program.c
TransformFeedback *newTransformFeedback(GLMContext ctx, GLuint name);
TransformFeedback *findTransformFeedback(GLMContext ctx, GLuint name);
TransformFeedback *getTransformFeedback(GLMContext ctx, GLuint name);

// Forward declaration for texture lookup from textures.c
extern Texture *findTexture(GLMContext ctx, GLuint texture);
extern Texture *currentTexture(GLMContext ctx, GLuint index);

// Forward declarations for program reflection from program.c
extern GLint programResourceLocation(GLMContext ctx, GLuint program, GLenum programInterface, const GLchar *name);
extern GLint programResourceLocationIndex(GLMContext ctx, GLuint program, GLenum programInterface, const GLchar *name);
extern ProgramPipeline *findProgramPipeline(GLMContext ctx, GLuint pipeline);
extern Program *findProgram(GLMContext ctx, GLuint program);
extern Shader *findShader(GLMContext ctx, GLuint shader);
extern bool validShaderType(GLenum shadertype);

// Forward declarations for the KHR_debug label store from error.c
extern void mglObjectLabelFetch(GLMContext ctx, GLenum identifier, GLuint name, GLsizei bufSize, GLsizei *length, GLchar *label);
extern void mglObjectPtrLabelFetch(GLMContext ctx, const void *ptr, GLsizei bufSize, GLsizei *length, GLchar *label);





void mglBeginTransformFeedback(GLMContext ctx, GLenum primitiveMode)
{
	// a bad mode is a bad argument, so it is caught ahead of the state checks
	switch (primitiveMode)
	{
		case GL_POINTS:
		case GL_LINES:
		case GL_TRIANGLES:
			break;

		default:
			ERROR_RETURN(GL_INVALID_ENUM);
	}

	if (!STATE(transform_feedback))
	{
		STATE(error) = GL_INVALID_OPERATION;
		return;
	}

	if (STATE(transform_feedback)->active)
	{
		STATE(error) = GL_INVALID_OPERATION;
		return;
	}

	// GL 4.6 section 13.2.2: capture needs somewhere to go. With no program,
	// no recorded varyings, or no buffer on a binding point it would use,
	// there is nothing to begin.
	{
		TransformFeedback *xfb = STATE(transform_feedback);
		// With a pipeline bound instead of a program, the varyings belong to
		// whichever program supplies the last stage before the rasteriser.
		Program *prog = STATE(program);

		if (prog == NULL && STATE(program_pipeline))
		{
			static const int order[] = { _GEOMETRY_SHADER, _TESS_EVALUATION_SHADER, _VERTEX_SHADER };

			for (unsigned i = 0; i < sizeof(order) / sizeof(order[0]); i++)
				if (STATE(program_pipeline)->stage_programs[order[i]])
				{
					prog = STATE(program_pipeline)->stage_programs[order[i]];
					break;
				}
		}

		GLsizei recorded = prog ? prog->xfb_varying_count : 0;
		GLuint needed = 0;

		if (prog && prog->xfb_shader_buffers)
			needed = prog->xfb_shader_buffers;
		else if (recorded > 0)
		{
			GLsizei buffers = 1;

			// one buffer each, or one more for every gl_NextBuffer
			for (GLsizei v = 0; v < recorded; v++)
				if (prog->xfb_buffer_mode == GL_SEPARATE_ATTRIBS ? v > 0 :
				    !strcmp(prog->xfb_varyings[v], "gl_NextBuffer"))
					buffers++;

			for (GLsizei b = 0; b < buffers && b < MAX_TF_BUFFERS; b++)
				needed |= 1u << b;
		}

		if (prog == NULL || needed == 0)
		{
			STATE(error) = GL_INVALID_OPERATION;
			return;
		}

		// glBindBufferBase records into the context's binding points and
		// glTransformFeedbackBufferBase into the object's own; either one
		// counts as a place for the capture to land.
		BufferBaseTarget *bound = STATE(buffer_base)[_TRANSFORM_FEEDBACK_BUFFER].buffers;

		for (GLuint i = 0; i < MAX_TF_BUFFERS; i++)
			if ((needed >> i) & 1u && xfb->buffers[i].buf == NULL && bound[i].buf == NULL)
			{
				STATE(error) = GL_INVALID_OPERATION;
				return;
			}
	}

	STATE(transform_feedback)->active = GL_TRUE;
	STATE(transform_feedback)->paused = GL_FALSE;
	STATE(transform_feedback)->primitive_mode = primitiveMode;

	// capture starts at the front of the buffers again
	STATE(transform_feedback)->vertices_recorded = 0;
}



void mglBindTransformFeedback(GLMContext ctx, GLenum target, GLuint id)
{
    if (target != GL_TRANSFORM_FEEDBACK)
    {
        STATE(error) = GL_INVALID_ENUM;
        return;
    }

    // Can't bind if current transform feedback is active and not paused
    if (STATE(transform_feedback) && 
        STATE(transform_feedback)->active && 
        !STATE(transform_feedback)->paused)
    {
        STATE(error) = GL_INVALID_OPERATION;
        return;
    }

    // GL 4.6 section 13.2: name zero is the default transform feedback object.
    // It is a real object that is always there, not the absence of one --
    // treating it as NULL made glBeginTransformFeedback fail before any
    // application had bound anything.
    TransformFeedback *ptr = getTransformFeedback(ctx, id);

    if (ptr)
    {
        ptr->target = target;
        ptr->created = GL_TRUE;
        STATE(transform_feedback) = ptr;
    }
}





void mglColorMaski(GLMContext ctx, GLuint index, GLboolean r, GLboolean g, GLboolean b, GLboolean a)
{
	ERROR_CHECK_RETURN(index < MAX_COLOR_ATTACHMENTS, GL_INVALID_VALUE);

	// only the named draw buffer changes; the others keep their own mask
	STATE(caps.use_color_mask[index]) = !(r && g && b && a);

	ctx->state.var.color_writemask[index][0] = r;
	ctx->state.var.color_writemask[index][1] = g;
	ctx->state.var.color_writemask[index][2] = b;
	ctx->state.var.color_writemask[index][3] = a;

	ctx->state.dirty_bits |= DIRTY_RENDER_STATE | DIRTY_ALPHA_STATE;
}

void mglColorP3ui(GLMContext ctx, GLenum type, GLuint color)
{
	// Packed color - deprecated, no-op
	(void)type;
	(void)color;
}

void mglColorP3uiv(GLMContext ctx, GLenum type, const GLuint *color)
{
	// Packed color - deprecated, no-op
	(void)type;
	(void)color;
}

void mglColorP4ui(GLMContext ctx, GLenum type, GLuint color)
{
	// Packed color - deprecated, no-op
	(void)type;
	(void)color;
}

void mglColorP4uiv(GLMContext ctx, GLenum type, const GLuint *color)
{
	// Packed color - deprecated, no-op
	(void)type;
	(void)color;
}

// Targets glCopyImageSubData accepts. Buffer textures and the individual
// cube faces are excluded by name in the spec.
static bool copyImageTargetValid(GLenum target)
{
	switch (target)
	{
		case GL_RENDERBUFFER:
		case GL_TEXTURE_1D:
		case GL_TEXTURE_1D_ARRAY:
		case GL_TEXTURE_2D:
		case GL_TEXTURE_2D_ARRAY:
		case GL_TEXTURE_2D_MULTISAMPLE:
		case GL_TEXTURE_2D_MULTISAMPLE_ARRAY:
		case GL_TEXTURE_3D:
		case GL_TEXTURE_CUBE_MAP:
		case GL_TEXTURE_CUBE_MAP_ARRAY:
		case GL_TEXTURE_RECTANGLE:
			return true;
	}

	return false;
}

// glCopyImageSubData names a texture or a renderbuffer, and they live in
// different tables. A renderbuffer carries the texture it is backed by.
static Texture *copyImageObject(GLMContext ctx, GLenum target, GLuint name)
{
	if (target == GL_RENDERBUFFER)
	{
		Renderbuffer *rbo = findRenderbuffer(ctx, name);

		return rbo ? rbo->tex : NULL;
	}

	return findTexture(ctx, name);
}

// Two images are copy-compatible when they hold the same number of bits per
// texel, or -- for compressed pairs -- the same block size. GL 4.6 table 8.22.
static bool copyImageFormatsCompatible(GLenum a, GLenum b)
{
	const MGLFormatDesc *da = mglFormatDesc(a);
	const MGLFormatDesc *db = mglFormatDesc(b);
	bool ca, cb;

	if (!da || !db)
		return false;

	if (a == b)
		return true;

	ca = mglFormatIsCompressed(a);
	cb = mglFormatIsCompressed(b);

	// a compressed image only copies to an uncompressed one of the same
	// block size, and the block dimensions have to line up
	if (ca != cb)
	{
		const MGLFormatDesc *cd = ca ? da : db;
		const MGLFormatDesc *ud = ca ? db : da;

		return cd->bytes_per_block == ud->bytes_per_block;
	}

	if (ca && cb)
		return da->block_w == db->block_w && da->block_h == db->block_h &&
		       da->bytes_per_block == db->bytes_per_block;

	return da->bytes_per_block == db->bytes_per_block;
}

static GLuint copyImageLevelWidth(const Texture *t, GLint level)
{
	if (level < 0 || (GLuint)level >= t->mipmap_levels || !t->faces[0].levels)
		return 0;

	return t->faces[0].levels[level].width;
}

static GLuint copyImageLevelHeight(const Texture *t, GLint level)
{
	if (level < 0 || (GLuint)level >= t->mipmap_levels || !t->faces[0].levels)
		return 0;

	// a 1D array keeps its layer count where a height would go, but the copy
	// reaches its layers through z; an image in it is one texel tall
	if (t->target == GL_TEXTURE_1D || t->target == GL_TEXTURE_1D_ARRAY)
		return 1;

	return t->faces[0].levels[level].height ? t->faces[0].levels[level].height : 1;
}

// How many slices or 3D samples the level has along z.
static GLuint copyImageLevelDepth(const Texture *t, GLint level)
{
	switch (t->target)
	{
		case GL_TEXTURE_2D_ARRAY:
		case GL_TEXTURE_CUBE_MAP_ARRAY:
		case GL_TEXTURE_2D_MULTISAMPLE_ARRAY:
			return t->depth ? t->depth : 1;

		case GL_TEXTURE_1D_ARRAY:
			return t->height ? t->height : 1;

		case GL_TEXTURE_CUBE_MAP:
			return 6;

		case GL_TEXTURE_3D:
			if (level >= 0 && (GLuint)level < t->mipmap_levels && t->faces[0].levels)
				return t->faces[0].levels[level].depth ? t->faces[0].levels[level].depth : 1;
			return 1;
	}

	return 1;
}

static bool copyImageLevelExists(const Texture *t, GLint level)
{
	return level >= 0 && (GLuint)level < t->mipmap_levels &&
	       t->faces[0].levels && t->faces[0].levels[level].width > 0;
}

// GL 4.6 section 8.17: every level the app has selected between BASE_LEVEL and
// MAX_LEVEL has to exist, or the texture is incomplete and cannot be copied.
static bool copyImageTexComplete(const Texture *t)
{
	GLuint base = t->params.base_level;
	GLuint last = t->params.max_level;

	if (t->mipmap_levels == 0 || !t->faces[0].levels)
		return false;

	if (base >= t->mipmap_levels)
		return false;

	if (last >= t->mipmap_levels)
		last = t->mipmap_levels - 1;

	for (GLuint l = base; l <= last; l++)
		if (!copyImageLevelExists(t, (GLint)l))
			return false;

	return true;
}

void mglCopyImageSubData(GLMContext ctx, GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei srcWidth, GLsizei srcHeight, GLsizei srcDepth)
{
	Texture *srcTex, *dstTex;
	const MGLFormatDesc *sd;

	ERROR_CHECK_RETURN(copyImageTargetValid(srcTarget), GL_INVALID_ENUM);
	ERROR_CHECK_RETURN(copyImageTargetValid(dstTarget), GL_INVALID_ENUM);

	srcTex = copyImageObject(ctx, srcTarget, srcName);
	dstTex = copyImageObject(ctx, dstTarget, dstName);

	ERROR_CHECK_RETURN(srcTex && dstTex, GL_INVALID_VALUE);

	// the target has to name what the object actually is
	ERROR_CHECK_RETURN(srcTarget == GL_RENDERBUFFER || srcTex->target == srcTarget, GL_INVALID_ENUM);
	ERROR_CHECK_RETURN(dstTarget == GL_RENDERBUFFER || dstTex->target == dstTarget, GL_INVALID_ENUM);

	ERROR_CHECK_RETURN(srcWidth >= 0 && srcHeight >= 0 && srcDepth >= 0, GL_INVALID_VALUE);
	ERROR_CHECK_RETURN(srcX >= 0 && srcY >= 0 && srcZ >= 0, GL_INVALID_VALUE);
	ERROR_CHECK_RETURN(dstX >= 0 && dstY >= 0 && dstZ >= 0, GL_INVALID_VALUE);

	// a renderbuffer has one image and no mip chain
	if (srcTarget == GL_RENDERBUFFER)
		ERROR_CHECK_RETURN(srcLevel == 0, GL_INVALID_VALUE);
	if (dstTarget == GL_RENDERBUFFER)
		ERROR_CHECK_RETURN(dstLevel == 0, GL_INVALID_VALUE);

	ERROR_CHECK_RETURN(copyImageLevelExists(srcTex, srcLevel), GL_INVALID_VALUE);
	ERROR_CHECK_RETURN(copyImageLevelExists(dstTex, dstLevel), GL_INVALID_VALUE);

	// an incomplete texture has nothing to copy. A renderbuffer has exactly
	// one image, so completeness does not apply to it.
	ERROR_CHECK_RETURN(srcTarget == GL_RENDERBUFFER || copyImageTexComplete(srcTex),
	                   GL_INVALID_OPERATION);
	ERROR_CHECK_RETURN(dstTarget == GL_RENDERBUFFER || copyImageTexComplete(dstTex),
	                   GL_INVALID_OPERATION);

	ERROR_CHECK_RETURN(srcTex->samples == dstTex->samples, GL_INVALID_OPERATION);

	ERROR_CHECK_RETURN(copyImageFormatsCompatible(srcTex->internalformat,
	                                              dstTex->internalformat), GL_INVALID_OPERATION);

	// a compressed image is addressed in whole blocks
	sd = mglFormatDesc(srcTex->internalformat);

	if (sd && mglFormatIsCompressed(srcTex->internalformat) && sd->block_w > 1)
	{
		GLuint bw = sd->block_w, bh = sd->block_h;

		ERROR_CHECK_RETURN(srcX % bw == 0 && srcY % bh == 0, GL_INVALID_VALUE);
		ERROR_CHECK_RETURN(dstX % bw == 0 && dstY % bh == 0, GL_INVALID_VALUE);

		// the tail of the image may be a partial block
		ERROR_CHECK_RETURN(srcWidth % bw == 0 ||
		                   (GLuint)(srcX + srcWidth) == copyImageLevelWidth(srcTex, srcLevel),
		                   GL_INVALID_VALUE);
		ERROR_CHECK_RETURN(srcHeight % bh == 0 ||
		                   (GLuint)(srcY + srcHeight) == copyImageLevelHeight(srcTex, srcLevel),
		                   GL_INVALID_VALUE);
	}

	// neither region may run off the end of its image
	ERROR_CHECK_RETURN((GLuint)(srcX + srcWidth)  <= copyImageLevelWidth(srcTex, srcLevel)  &&
	                   (GLuint)(srcY + srcHeight) <= copyImageLevelHeight(srcTex, srcLevel) &&
	                   (GLuint)(srcZ + srcDepth)  <= copyImageLevelDepth(srcTex, srcLevel),
	                   GL_INVALID_VALUE);

	ERROR_CHECK_RETURN((GLuint)(dstX + srcWidth)  <= copyImageLevelWidth(dstTex, dstLevel)  &&
	                   (GLuint)(dstY + srcHeight) <= copyImageLevelHeight(dstTex, dstLevel) &&
	                   (GLuint)(dstZ + srcDepth)  <= copyImageLevelDepth(dstTex, dstLevel),
	                   GL_INVALID_VALUE);

	if (srcWidth == 0 || srcHeight == 0 || srcDepth == 0)
		return;

	// The Metal textures are created on bind, which mtlCopyImageSubData does
	// itself. Refusing here because mtl_data is still NULL rejected every copy.
	ctx->mtl_funcs.mtlCopyImageSubData(ctx, srcTex, srcLevel, srcX, srcY, srcZ,
	                                    dstTex, dstLevel, dstX, dstY, dstZ,
	                                    srcWidth, srcHeight, srcDepth);
}

void mglCreateProgramPipelines(GLMContext ctx, GLsizei n, GLuint *pipelines)
{
	ERROR_CHECK_RETURN(n >= 0, GL_INVALID_VALUE);

	for (GLsizei i = 0; i < n; i++)
	{
		mglGenProgramPipelines(ctx, 1, &pipelines[i]);

		ProgramPipeline *pp = findProgramPipeline(ctx, pipelines[i]);

		if (pp)
			pp->created = GL_TRUE;
	}
}


GLuint  mglCreateShaderProgramv(GLMContext ctx, GLenum type, GLsizei count, const GLchar *const*strings)
{
	ERROR_CHECK_RETURN_VALUE(validShaderType(type), GL_INVALID_ENUM, 0);
	ERROR_CHECK_RETURN_VALUE(count >= 0, GL_INVALID_VALUE, 0);

	GLuint shader = mglCreateShader(ctx, type);
	if (!shader)
		return 0;

	mglShaderSource(ctx, shader, count, strings, NULL);
	mglCompileShader(ctx, shader);

	GLuint program = mglCreateProgram(ctx);
	if (!program) {
		mglDeleteShader(ctx, shader);
		return 0;
	}

	// what this call makes is always a separable program
	Program *pptr = findProgram(ctx, program);
	GLint compiled = GL_FALSE;

	mglGetShaderiv(ctx, shader, GL_COMPILE_STATUS, &compiled);

	if (pptr)
		pptr->separable = GL_TRUE;

	// the spec's own sequence: only a shader that compiled is linked, and the
	// shader's log goes onto the program either way
	if (compiled)
	{
		mglAttachShader(ctx, program, shader);
		mglLinkProgram(ctx, program);
		mglDetachShader(ctx, program, shader);
	}
	else if (pptr)
	{
		Shader *sptr = findShader(ctx, shader);

		free(pptr->log);
		pptr->log = strdup(sptr && sptr->log ? sptr->log : "the shader did not compile");
		pptr->link_status = GL_FALSE;
	}

	mglDeleteShader(ctx, shader);

	return program;
}

void mglCreateTransformFeedbacks(GLMContext ctx, GLsizei n, GLuint *ids)
{
	ERROR_CHECK_RETURN(n >= 0, GL_INVALID_VALUE);

	for (GLsizei i = 0; i < n; i++)
	{
		TransformFeedback *ptr;

		mglGenTransformFeedbacks(ctx, 1, &ids[i]);

		// unlike glGen, this one makes the object, without binding it
		ptr = getTransformFeedback(ctx, ids[i]);

		if (ptr)
			ptr->created = GL_TRUE;
	}
}





void mglDeleteTransformFeedbacks(GLMContext ctx, GLsizei n, const GLuint *ids)
{
    for (GLsizei i = 0; i < n; i++)
    {
        if (ids[i] == 0)
            continue;
            
        TransformFeedback *ptr = findTransformFeedback(ctx, ids[i]);
        if (!ptr)
            continue;
            
        // Can't delete if active
        if (ptr->active)
        {
            STATE(error) = GL_INVALID_OPERATION;
            continue;
        }
            
        // deleting the bound one falls back to the default object, not to
        // nothing -- a null binding kills the next draw in any later test
        if (STATE(transform_feedback) && STATE(transform_feedback)->name == ids[i])
        {
            STATE(transform_feedback) = getTransformFeedback(ctx, 0);
        }
        
        // Remove from hash table and free
        deleteHashElement(&STATE(transform_feedback_table), ids[i]);
        free(ptr);
    }
}



void mglDepthRangef(GLMContext ctx, GLfloat n, GLfloat f)
{
	mglDepthRange(ctx, (GLdouble)n, (GLdouble)f);
}








void mglEndTransformFeedback(GLMContext ctx)
{
	if (!STATE(transform_feedback) || !STATE(transform_feedback)->active)
	{
		STATE(error) = GL_INVALID_OPERATION;
		return;
	}

	STATE(transform_feedback)->active = GL_FALSE;
	STATE(transform_feedback)->paused = GL_FALSE;

	// a replay draws what this capture came to, and the next Begin is about
	// to reset the cursor
	STATE(transform_feedback)->vertices_captured = STATE(transform_feedback)->vertices_recorded;
	STATE(transform_feedback)->ever_ended = GL_TRUE;
}


void mglGenTransformFeedbacks(GLMContext ctx, GLsizei n, GLuint *ids)
{
    for (GLsizei i = 0; i < n; i++)
    {
        ids[i] = getNewName(&STATE(transform_feedback_table));
        getTransformFeedback(ctx, ids[i]);
    }
}


// mglGetActiveSubroutineName now lives in program.c, with the rest of the
// subroutine queries.












// Where Metal puts the samples. These are the patterns the hardware uses by
// default, and they are what gl_SamplePosition reports in a shader, so the
// query has to answer the same thing. Saying 0.5, 0.5 for every sample made
// the two disagree, which is the one thing GL does pin down.
static const GLfloat mgl_sample_positions_2[2][2] = {
	{ 0.75f, 0.75f }, { 0.25f, 0.25f }
};

static const GLfloat mgl_sample_positions_4[4][2] = {
	{ 0.375f, 0.125f }, { 0.875f, 0.375f }, { 0.125f, 0.625f }, { 0.625f, 0.875f }
};

static const GLfloat mgl_sample_positions_8[8][2] = {
	{ 0.5625f, 0.3125f }, { 0.4375f, 0.6875f }, { 0.8125f, 0.5625f }, { 0.3125f, 0.1875f },
	{ 0.1875f, 0.8125f }, { 0.0625f, 0.4375f }, { 0.6875f, 0.9375f }, { 0.9375f, 0.0625f }
};

void mglGetMultisamplefv(GLMContext ctx, GLenum pname, GLuint index, GLfloat *val)
{
	GLsizei samples;

	ERROR_CHECK_RETURN(pname == GL_SAMPLE_POSITION, GL_INVALID_ENUM);
	ERROR_CHECK_RETURN(val, GL_INVALID_VALUE);

	samples = mglDrawFramebufferSamples(ctx);

	if (samples < 1)
		samples = 1;

	ERROR_CHECK_RETURN((GLsizei)index < samples, GL_INVALID_VALUE);

	switch (samples)
	{
		case 2:  val[0] = mgl_sample_positions_2[index][0];
		         val[1] = mgl_sample_positions_2[index][1];
		         break;
		case 4:  val[0] = mgl_sample_positions_4[index][0];
		         val[1] = mgl_sample_positions_4[index][1];
		         break;
		case 8:  val[0] = mgl_sample_positions_8[index][0];
		         val[1] = mgl_sample_positions_8[index][1];
		         break;
		default: val[0] = 0.5f;     // one sample sits in the middle
		         val[1] = 0.5f;
		         break;
	}
}

void mglGetObjectLabel(GLMContext ctx, GLenum identifier, GLuint name, GLsizei bufSize, GLsizei *length, GLchar *label)
{
	mglObjectLabelFetch(ctx, identifier, name, bufSize, length, label);
}

void mglGetObjectPtrLabel(GLMContext ctx, const void *ptr, GLsizei bufSize, GLsizei *length, GLchar *label)
{
	mglObjectPtrLabelFetch(ctx, ptr, bufSize, length, label);
}



void mglGetProgramPipelineInfoLog(GLMContext ctx, GLuint pipeline, GLsizei bufSize, GLsizei *length, GLchar *infoLog)
{
	ERROR_CHECK_RETURN(findProgramPipeline(ctx, pipeline), GL_INVALID_VALUE);
	ERROR_CHECK_RETURN(bufSize >= 0, GL_INVALID_VALUE);

	// MGL's pipelines never log anything, so the log is always empty
	if (length) *length = 0;
	if (infoLog && bufSize > 0) infoLog[0] = '\0';
}



GLint  mglGetProgramResourceLocation(GLMContext ctx, GLuint program, GLenum programInterface, const GLchar *name)
{
	return programResourceLocation(ctx, program, programInterface, name);
}

GLint  mglGetProgramResourceLocationIndex(GLMContext ctx, GLuint program, GLenum programInterface, const GLchar *name)
{
	return programResourceLocationIndex(ctx, program, programInterface, name);
}














void mglGetShaderPrecisionFormat(GLMContext ctx, GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision)
{
	ERROR_CHECK_RETURN(shadertype == GL_VERTEX_SHADER || shadertype == GL_FRAGMENT_SHADER, GL_INVALID_ENUM);

	switch (precisiontype)
	{
		case GL_LOW_FLOAT:
		case GL_MEDIUM_FLOAT:
		case GL_HIGH_FLOAT:
		case GL_LOW_INT:
		case GL_MEDIUM_INT:
		case GL_HIGH_INT:
			break;

		default:
			ERROR_RETURN(GL_INVALID_ENUM);
	}

	// Metal is full precision throughout, so every type reports the same
	if (range) {
		range[0] = 127;
		range[1] = 127;
	}
	if (precision) {
		*precision = 23;
	}
}












void mglGetnMapdv(GLMContext ctx, GLenum target, GLenum query, GLsizei bufSize, GLdouble *v)
{
	// TODO: Implement
	(void)ctx;
}

void mglGetnMapfv(GLMContext ctx, GLenum target, GLenum query, GLsizei bufSize, GLfloat *v)
{
	// TODO: Implement
	(void)ctx;
}

void mglGetnMapiv(GLMContext ctx, GLenum target, GLenum query, GLsizei bufSize, GLint *v)
{
	// TODO: Implement
	(void)ctx;
}

void mglGetnPixelMapfv(GLMContext ctx, GLenum map, GLsizei bufSize, GLfloat *values)
{
	// TODO: Implement
	(void)ctx;
}

void mglGetnPixelMapuiv(GLMContext ctx, GLenum map, GLsizei bufSize, GLuint *values)
{
	// TODO: Implement
	(void)ctx;
}

void mglGetnPixelMapusv(GLMContext ctx, GLenum map, GLsizei bufSize, GLushort *values)
{
	// TODO: Implement
	(void)ctx;
}







GLboolean mglIsTransformFeedback(GLMContext ctx, GLuint id)
{
	TransformFeedback *ptr = findTransformFeedback(ctx, id);
	return (ptr && ptr->created) ? GL_TRUE : GL_FALSE;
}




void mglNormalP3ui(GLMContext ctx, GLenum type, GLuint coords)
{
	// TODO: Implement
	(void)ctx;
}

void mglNormalP3uiv(GLMContext ctx, GLenum type, const GLuint *coords)
{
	// TODO: Implement
	(void)ctx;
}





void mglPauseTransformFeedback(GLMContext ctx)
{
	if (!STATE(transform_feedback) || !STATE(transform_feedback)->active || STATE(transform_feedback)->paused)
	{
		STATE(error) = GL_INVALID_OPERATION;
		return;
	}

	STATE(transform_feedback)->paused = GL_TRUE;
}
























































void mglProvokingVertex(GLMContext ctx, GLenum mode)
{
	// Set provoking vertex mode - no-op
	if (mode != GL_FIRST_VERTEX_CONVENTION && mode != GL_LAST_VERTEX_CONVENTION) {
		STATE(error) = GL_INVALID_ENUM;
		return;
	}
	// State not tracked
}





void mglResumeTransformFeedback(GLMContext ctx)
{
	if (!STATE(transform_feedback) || !STATE(transform_feedback)->active || !STATE(transform_feedback)->paused)
	{
		STATE(error) = GL_INVALID_OPERATION;
		return;
	}

	STATE(transform_feedback)->paused = GL_FALSE;
}





void mglSecondaryColorP3ui(GLMContext ctx, GLenum type, GLuint color)
{
	// TODO: Implement
	(void)ctx;
}

void mglSecondaryColorP3uiv(GLMContext ctx, GLenum type, const GLuint *color)
{
	// TODO: Implement
	(void)ctx;
}




// TexBuffer moved to texture_buffer.c

// TexBufferRange moved to texture_buffer.c

// TexStorage2DMultisample moved to texture_multisample.c

// TexStorage3DMultisample moved to texture_multisample.c















































































void mglVertexP2ui(GLMContext ctx, GLenum type, GLuint value)
{
	// TODO: Implement
	(void)ctx;
}

void mglVertexP2uiv(GLMContext ctx, GLenum type, const GLuint *value)
{
	// TODO: Implement
	(void)ctx;
}

void mglVertexP3ui(GLMContext ctx, GLenum type, GLuint value)
{
	// TODO: Implement
	(void)ctx;
}

void mglVertexP3uiv(GLMContext ctx, GLenum type, const GLuint *value)
{
	// TODO: Implement
	(void)ctx;
}

void mglVertexP4ui(GLMContext ctx, GLenum type, GLuint value)
{
	// TODO: Implement
	(void)ctx;
}

void mglVertexP4uiv(GLMContext ctx, GLenum type, const GLuint *value)
{
	// TODO: Implement
	(void)ctx;
}




#ifdef MGL_GL_ES
void  mglBlendBarrier(GLMContext ctx)
{
    // Metal already orders fragment writes to the same pixel
}

void mglPrimitiveBoundingBox(GLMContext ctx, GLfloat minX, GLfloat minY, GLfloat minZ, GLfloat minW, GLfloat maxX, GLfloat maxY, GLfloat maxZ, GLfloat maxW)
{
    
}
#endif
