//
// Autogenerated from gl.xml
//
// Mike Larson
//
// October 2021
//

#include <assert.h>

#include "mgl.h"
#include "mgl_log.h"

// Forward declarations for transform feedback functions from program.c
TransformFeedback *newTransformFeedback(GLMContext ctx, GLuint name);
TransformFeedback *findTransformFeedback(GLMContext ctx, GLuint name);
TransformFeedback *getTransformFeedback(GLMContext ctx, GLuint name);

// Forward declaration for texture lookup from textures.c
extern Texture *findTexture(GLMContext ctx, GLuint texture);
extern Texture *currentTexture(GLMContext ctx, GLuint index);

// Forward declarations for program reflection from program.c
extern GLint programResourceLocation(GLMContext ctx, GLuint program, GLenum programInterface, const GLchar *name);
extern GLint programResourceLocationIndex(GLMContext ctx, GLuint program, GLenum programInterface, const GLchar *name);
extern ProgramPipeline *findProgramPipeline(GLMContext ctx, GLuint pipeline);
extern Program *findProgram(GLMContext ctx, GLuint program);
extern bool validShaderType(GLenum shadertype);

// Forward declarations for the KHR_debug label store from error.c
extern void mglObjectLabelFetch(GLMContext ctx, GLenum identifier, GLuint name, GLsizei bufSize, GLsizei *length, GLchar *label);
extern void mglObjectPtrLabelFetch(GLMContext ctx, const void *ptr, GLsizei bufSize, GLsizei *length, GLchar *label);





void mglBeginTransformFeedback(GLMContext ctx, GLenum primitiveMode)
{
	// a bad mode is a bad argument, so it is caught ahead of the state checks
	switch (primitiveMode)
	{
		case GL_POINTS:
		case GL_LINES:
		case GL_TRIANGLES:
			break;

		default:
			ERROR_RETURN(GL_INVALID_ENUM);
	}

	if (!STATE(transform_feedback))
	{
		STATE(error) = GL_INVALID_OPERATION;
		return;
	}

	if (STATE(transform_feedback)->active)
	{
		STATE(error) = GL_INVALID_OPERATION;
		return;
	}

	STATE(transform_feedback)->active = GL_TRUE;
	STATE(transform_feedback)->paused = GL_FALSE;
	STATE(transform_feedback)->primitive_mode = primitiveMode;
}



void mglBindTransformFeedback(GLMContext ctx, GLenum target, GLuint id)
{
    if (target != GL_TRANSFORM_FEEDBACK)
    {
        STATE(error) = GL_INVALID_ENUM;
        return;
    }

    // Can't bind if current transform feedback is active and not paused
    if (STATE(transform_feedback) && 
        STATE(transform_feedback)->active && 
        !STATE(transform_feedback)->paused)
    {
        STATE(error) = GL_INVALID_OPERATION;
        return;
    }

    if (id == 0)
    {
        // Unbind transform feedback
        STATE(transform_feedback) = NULL;
    }
    else
    {
        TransformFeedback *ptr = getTransformFeedback(ctx, id);
        if (ptr)
        {
            ptr->target = target;
            STATE(transform_feedback) = ptr;
        }
    }
}





void mglColorMaski(GLMContext ctx, GLuint index, GLboolean r, GLboolean g, GLboolean b, GLboolean a)
{
	ERROR_CHECK_RETURN(index < MAX_COLOR_ATTACHMENTS, GL_INVALID_VALUE);

	// only the named draw buffer changes; the others keep their own mask
	STATE(caps.use_color_mask[index]) = !(r && g && b && a);

	ctx->state.var.color_writemask[index][0] = r;
	ctx->state.var.color_writemask[index][1] = g;
	ctx->state.var.color_writemask[index][2] = b;
	ctx->state.var.color_writemask[index][3] = a;

	ctx->state.dirty_bits |= DIRTY_RENDER_STATE | DIRTY_ALPHA_STATE;
}

void mglColorP3ui(GLMContext ctx, GLenum type, GLuint color)
{
	// Packed color - deprecated, no-op
	(void)type;
	(void)color;
}

void mglColorP3uiv(GLMContext ctx, GLenum type, const GLuint *color)
{
	// Packed color - deprecated, no-op
	(void)type;
	(void)color;
}

void mglColorP4ui(GLMContext ctx, GLenum type, GLuint color)
{
	// Packed color - deprecated, no-op
	(void)type;
	(void)color;
}

void mglColorP4uiv(GLMContext ctx, GLenum type, const GLuint *color)
{
	// Packed color - deprecated, no-op
	(void)type;
	(void)color;
}

// Targets glCopyImageSubData accepts. Buffer textures and the individual
// cube faces are excluded by name in the spec.
static bool copyImageTargetValid(GLenum target)
{
	switch (target)
	{
		case GL_RENDERBUFFER:
		case GL_TEXTURE_1D:
		case GL_TEXTURE_1D_ARRAY:
		case GL_TEXTURE_2D:
		case GL_TEXTURE_2D_ARRAY:
		case GL_TEXTURE_2D_MULTISAMPLE:
		case GL_TEXTURE_2D_MULTISAMPLE_ARRAY:
		case GL_TEXTURE_3D:
		case GL_TEXTURE_CUBE_MAP:
		case GL_TEXTURE_CUBE_MAP_ARRAY:
		case GL_TEXTURE_RECTANGLE:
			return true;
	}

	return false;
}

void mglCopyImageSubData(GLMContext ctx, GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei srcWidth, GLsizei srcHeight, GLsizei srcDepth)
{
	MGL_INFO("MGL: glCopyImageSubData src=%u dst=%u %dx%dx%d\n",
	        srcName, dstName, srcWidth, srcHeight, srcDepth);

	ERROR_CHECK_RETURN(copyImageTargetValid(srcTarget), GL_INVALID_ENUM);
	ERROR_CHECK_RETURN(copyImageTargetValid(dstTarget), GL_INVALID_ENUM);

	// Find source and destination textures
	Texture *srcTex = findTexture(ctx, srcName);
	Texture *dstTex = findTexture(ctx, dstName);

	ERROR_CHECK_RETURN(srcTex && dstTex, GL_INVALID_VALUE);
	
	if (!srcTex->mtl_data || !dstTex->mtl_data) {
		MGL_ERR("MGL ERROR: CopyImageSubData - no Metal data src=%p dst=%p\n",
		        srcTex->mtl_data, dstTex->mtl_data);
		return;
	}
	
	// Use Metal blit to copy texture regions
	ctx->mtl_funcs.mtlCopyImageSubData(ctx, srcTex, srcLevel, srcX, srcY, srcZ,
	                                    dstTex, dstLevel, dstX, dstY, dstZ,
	                                    srcWidth, srcHeight, srcDepth);
}

void mglCreateProgramPipelines(GLMContext ctx, GLsizei n, GLuint *pipelines)
{
	for (GLsizei i = 0; i < n; i++)
	{
		mglGenProgramPipelines(ctx, 1, &pipelines[i]);
	}
}


GLuint  mglCreateShaderProgramv(GLMContext ctx, GLenum type, GLsizei count, const GLchar *const*strings)
{
	GLuint shader = mglCreateShader(ctx, type);
	if (!shader)
		return 0;
	
	mglShaderSource(ctx, shader, count, strings, NULL);
	mglCompileShader(ctx, shader);
	
	GLuint program = mglCreateProgram(ctx);
	if (!program) {
		mglDeleteShader(ctx, shader);
		return 0;
	}
	
	mglAttachShader(ctx, program, shader);
	mglLinkProgram(ctx, program);

	// the spec detaches before deleting, so the program ends up with no
	// attached shaders at all
	mglDetachShader(ctx, program, shader);
	mglDeleteShader(ctx, shader);

	return program;
}

void mglCreateTransformFeedbacks(GLMContext ctx, GLsizei n, GLuint *ids)
{
	ERROR_CHECK_RETURN(n >= 0, GL_INVALID_VALUE);

	for (GLsizei i = 0; i < n; i++)
	{
		mglGenTransformFeedbacks(ctx, 1, &ids[i]);
	}
}





void mglDeleteTransformFeedbacks(GLMContext ctx, GLsizei n, const GLuint *ids)
{
    for (GLsizei i = 0; i < n; i++)
    {
        if (ids[i] == 0)
            continue;
            
        TransformFeedback *ptr = findTransformFeedback(ctx, ids[i]);
        if (!ptr)
            continue;
            
        // Can't delete if active
        if (ptr->active)
        {
            STATE(error) = GL_INVALID_OPERATION;
            continue;
        }
            
        // If deleting currently bound transform feedback, unbind it
        if (STATE(transform_feedback) && STATE(transform_feedback)->name == ids[i])
        {
            STATE(transform_feedback) = NULL;
        }
        
        // Remove from hash table and free
        deleteHashElement(&STATE(transform_feedback_table), ids[i]);
        free(ptr);
    }
}



void mglDepthRangef(GLMContext ctx, GLfloat n, GLfloat f)
{
	mglDepthRange(ctx, (GLdouble)n, (GLdouble)f);
}








void mglEndTransformFeedback(GLMContext ctx)
{
	if (!STATE(transform_feedback) || !STATE(transform_feedback)->active)
	{
		STATE(error) = GL_INVALID_OPERATION;
		return;
	}

	STATE(transform_feedback)->active = GL_FALSE;
	STATE(transform_feedback)->paused = GL_FALSE;
}


void mglGenTransformFeedbacks(GLMContext ctx, GLsizei n, GLuint *ids)
{
    for (GLsizei i = 0; i < n; i++)
    {
        ids[i] = getNewName(&STATE(transform_feedback_table));
        getTransformFeedback(ctx, ids[i]);
    }
}


void mglGetActiveSubroutineName(GLMContext ctx, GLuint program, GLenum shadertype, GLuint index, GLsizei bufSize, GLsizei *length, GLchar *name)
{
	ERROR_CHECK_RETURN(findProgram(ctx, program), GL_INVALID_VALUE);
	ERROR_CHECK_RETURN(bufSize >= 0, GL_INVALID_VALUE);
	ERROR_CHECK_RETURN(validShaderType(shadertype), GL_INVALID_ENUM);

	// MGL's linker captures no subroutines, so every index is out of range
	ERROR_RETURN(GL_INVALID_VALUE);
}












void mglGetMultisamplefv(GLMContext ctx, GLenum pname, GLuint index, GLfloat *val)
{
	// Get sample positions for multisample rendering
	if (pname != GL_SAMPLE_POSITION) {
		STATE(error) = GL_INVALID_ENUM;
		return;
	}
	
	// Metal uses fixed sample positions based on sample count
	// Return reasonable default positions (center for simplicity)
	val[0] = 0.5f;
	val[1] = 0.5f;
}

void mglGetObjectLabel(GLMContext ctx, GLenum identifier, GLuint name, GLsizei bufSize, GLsizei *length, GLchar *label)
{
	mglObjectLabelFetch(ctx, identifier, name, bufSize, length, label);
}

void mglGetObjectPtrLabel(GLMContext ctx, const void *ptr, GLsizei bufSize, GLsizei *length, GLchar *label)
{
	mglObjectPtrLabelFetch(ctx, ptr, bufSize, length, label);
}



void mglGetProgramPipelineInfoLog(GLMContext ctx, GLuint pipeline, GLsizei bufSize, GLsizei *length, GLchar *infoLog)
{
	ERROR_CHECK_RETURN(findProgramPipeline(ctx, pipeline), GL_INVALID_OPERATION);
	ERROR_CHECK_RETURN(bufSize >= 0, GL_INVALID_VALUE);

	// MGL's pipelines never log anything, so the log is always empty
	if (length) *length = 0;
	if (infoLog && bufSize > 0) infoLog[0] = '\0';
}



GLint  mglGetProgramResourceLocation(GLMContext ctx, GLuint program, GLenum programInterface, const GLchar *name)
{
	return programResourceLocation(ctx, program, programInterface, name);
}

GLint  mglGetProgramResourceLocationIndex(GLMContext ctx, GLuint program, GLenum programInterface, const GLchar *name)
{
	return programResourceLocationIndex(ctx, program, programInterface, name);
}














void mglGetShaderPrecisionFormat(GLMContext ctx, GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision)
{
	ERROR_CHECK_RETURN(shadertype == GL_VERTEX_SHADER || shadertype == GL_FRAGMENT_SHADER, GL_INVALID_ENUM);

	switch (precisiontype)
	{
		case GL_LOW_FLOAT:
		case GL_MEDIUM_FLOAT:
		case GL_HIGH_FLOAT:
		case GL_LOW_INT:
		case GL_MEDIUM_INT:
		case GL_HIGH_INT:
			break;

		default:
			ERROR_RETURN(GL_INVALID_ENUM);
	}

	// Metal is full precision throughout, so every type reports the same
	if (range) {
		range[0] = 127;
		range[1] = 127;
	}
	if (precision) {
		*precision = 23;
	}
}












void mglGetnMapdv(GLMContext ctx, GLenum target, GLenum query, GLsizei bufSize, GLdouble *v)
{
	// TODO: Implement
	(void)ctx;
}

void mglGetnMapfv(GLMContext ctx, GLenum target, GLenum query, GLsizei bufSize, GLfloat *v)
{
	// TODO: Implement
	(void)ctx;
}

void mglGetnMapiv(GLMContext ctx, GLenum target, GLenum query, GLsizei bufSize, GLint *v)
{
	// TODO: Implement
	(void)ctx;
}

void mglGetnPixelMapfv(GLMContext ctx, GLenum map, GLsizei bufSize, GLfloat *values)
{
	// TODO: Implement
	(void)ctx;
}

void mglGetnPixelMapuiv(GLMContext ctx, GLenum map, GLsizei bufSize, GLuint *values)
{
	// TODO: Implement
	(void)ctx;
}

void mglGetnPixelMapusv(GLMContext ctx, GLenum map, GLsizei bufSize, GLushort *values)
{
	// TODO: Implement
	(void)ctx;
}







GLboolean mglIsTransformFeedback(GLMContext ctx, GLuint id)
{
	TransformFeedback *ptr = findTransformFeedback(ctx, id);
	return ptr ? GL_TRUE : GL_FALSE;
}




void mglNormalP3ui(GLMContext ctx, GLenum type, GLuint coords)
{
	// TODO: Implement
	(void)ctx;
}

void mglNormalP3uiv(GLMContext ctx, GLenum type, const GLuint *coords)
{
	// TODO: Implement
	(void)ctx;
}





void mglPauseTransformFeedback(GLMContext ctx)
{
	if (!STATE(transform_feedback) || !STATE(transform_feedback)->active || STATE(transform_feedback)->paused)
	{
		STATE(error) = GL_INVALID_OPERATION;
		return;
	}

	STATE(transform_feedback)->paused = GL_TRUE;
}
























































void mglProvokingVertex(GLMContext ctx, GLenum mode)
{
	// Set provoking vertex mode - no-op
	if (mode != GL_FIRST_VERTEX_CONVENTION && mode != GL_LAST_VERTEX_CONVENTION) {
		STATE(error) = GL_INVALID_ENUM;
		return;
	}
	// State not tracked
}





void mglResumeTransformFeedback(GLMContext ctx)
{
	if (!STATE(transform_feedback) || !STATE(transform_feedback)->active || !STATE(transform_feedback)->paused)
	{
		STATE(error) = GL_INVALID_OPERATION;
		return;
	}

	STATE(transform_feedback)->paused = GL_FALSE;
}





void mglSecondaryColorP3ui(GLMContext ctx, GLenum type, GLuint color)
{
	// TODO: Implement
	(void)ctx;
}

void mglSecondaryColorP3uiv(GLMContext ctx, GLenum type, const GLuint *color)
{
	// TODO: Implement
	(void)ctx;
}




// TexBuffer moved to texture_buffer.c

// TexBufferRange moved to texture_buffer.c

// TexStorage2DMultisample moved to texture_multisample.c

// TexStorage3DMultisample moved to texture_multisample.c















































































void mglVertexP2ui(GLMContext ctx, GLenum type, GLuint value)
{
	// TODO: Implement
	(void)ctx;
}

void mglVertexP2uiv(GLMContext ctx, GLenum type, const GLuint *value)
{
	// TODO: Implement
	(void)ctx;
}

void mglVertexP3ui(GLMContext ctx, GLenum type, GLuint value)
{
	// TODO: Implement
	(void)ctx;
}

void mglVertexP3uiv(GLMContext ctx, GLenum type, const GLuint *value)
{
	// TODO: Implement
	(void)ctx;
}

void mglVertexP4ui(GLMContext ctx, GLenum type, GLuint value)
{
	// TODO: Implement
	(void)ctx;
}

void mglVertexP4uiv(GLMContext ctx, GLenum type, const GLuint *value)
{
	// TODO: Implement
	(void)ctx;
}




#ifdef MGL_GL_ES
void  mglBlendBarrier(GLMContext ctx)
{
    // Metal already orders fragment writes to the same pixel
}

void mglPrimitiveBoundingBox(GLMContext ctx, GLfloat minX, GLfloat minY, GLfloat minZ, GLfloat minW, GLfloat maxX, GLfloat maxY, GLfloat maxZ, GLfloat maxW)
{
    
}
#endif
