//
// Autogenerated from gl.xml
//
// Mike Larson
//
// October 2021
//

#include <assert.h>

#include "mgl.h"
#include "mgl_log.h"

// Forward declarations for transform feedback functions from program.c
TransformFeedback *newTransformFeedback(GLMContext ctx, GLuint name);
TransformFeedback *findTransformFeedback(GLMContext ctx, GLuint name);
TransformFeedback *getTransformFeedback(GLMContext ctx, GLuint name);

// Forward declaration for texture lookup from textures.c
extern Texture *findTexture(GLMContext ctx, GLuint texture);
extern Texture *currentTexture(GLMContext ctx, GLuint index);





void mglBeginTransformFeedback(GLMContext ctx, GLenum primitiveMode)
{
	if (!STATE(transform_feedback))
	{
		STATE(error) = GL_INVALID_OPERATION;
		return;
	}

	if (STATE(transform_feedback)->active)
	{
		STATE(error) = GL_INVALID_OPERATION;
		return;
	}

	STATE(transform_feedback)->active = GL_TRUE;
	STATE(transform_feedback)->paused = GL_FALSE;
	STATE(transform_feedback)->primitive_mode = primitiveMode;
}



void mglBindTransformFeedback(GLMContext ctx, GLenum target, GLuint id)
{
    if (target != GL_TRANSFORM_FEEDBACK)
    {
        STATE(error) = GL_INVALID_ENUM;
        return;
    }

    // Can't bind if current transform feedback is active and not paused
    if (STATE(transform_feedback) && 
        STATE(transform_feedback)->active && 
        !STATE(transform_feedback)->paused)
    {
        STATE(error) = GL_INVALID_OPERATION;
        return;
    }

    if (id == 0)
    {
        // Unbind transform feedback
        STATE(transform_feedback) = NULL;
    }
    else
    {
        TransformFeedback *ptr = getTransformFeedback(ctx, id);
        if (ptr)
        {
            ptr->target = target;
            STATE(transform_feedback) = ptr;
        }
    }
}





void mglColorMaski(GLMContext ctx, GLuint index, GLboolean r, GLboolean g, GLboolean b, GLboolean a)
{
	// Indexed color mask - use global mask for simplicity
	(void)index;
	mglColorMask(ctx, r, g, b, a);
}

void mglColorP3ui(GLMContext ctx, GLenum type, GLuint color)
{
	// Packed color - deprecated, no-op
	(void)type;
	(void)color;
}

void mglColorP3uiv(GLMContext ctx, GLenum type, const GLuint *color)
{
	// Packed color - deprecated, no-op
	(void)type;
	(void)color;
}

void mglColorP4ui(GLMContext ctx, GLenum type, GLuint color)
{
	// Packed color - deprecated, no-op
	(void)type;
	(void)color;
}

void mglColorP4uiv(GLMContext ctx, GLenum type, const GLuint *color)
{
	// Packed color - deprecated, no-op
	(void)type;
	(void)color;
}

void mglCopyImageSubData(GLMContext ctx, GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei srcWidth, GLsizei srcHeight, GLsizei srcDepth)
{
	MGL_INFO("MGL: glCopyImageSubData src=%u dst=%u %dx%dx%d\n",
	        srcName, dstName, srcWidth, srcHeight, srcDepth);
	
	// Find source and destination textures
	Texture *srcTex = findTexture(ctx, srcName);
	Texture *dstTex = findTexture(ctx, dstName);
	
	if (!srcTex || !dstTex) {
		MGL_ERR("MGL ERROR: CopyImageSubData - texture not found src=%p dst=%p\n",
		        srcTex, dstTex);
		return;
	}
	
	if (!srcTex->mtl_data || !dstTex->mtl_data) {
		MGL_ERR("MGL ERROR: CopyImageSubData - no Metal data src=%p dst=%p\n",
		        srcTex->mtl_data, dstTex->mtl_data);
		return;
	}
	
	// Use Metal blit to copy texture regions
	ctx->mtl_funcs.mtlCopyImageSubData(ctx, srcTex, srcLevel, srcX, srcY, srcZ,
	                                    dstTex, dstLevel, dstX, dstY, dstZ,
	                                    srcWidth, srcHeight, srcDepth);
}

void mglCreateProgramPipelines(GLMContext ctx, GLsizei n, GLuint *pipelines)
{
	for (GLsizei i = 0; i < n; i++)
	{
		mglGenProgramPipelines(ctx, 1, &pipelines[i]);
	}
}


GLuint  mglCreateShaderProgramv(GLMContext ctx, GLenum type, GLsizei count, const GLchar *const*strings)
{
	GLuint shader = mglCreateShader(ctx, type);
	if (!shader)
		return 0;
	
	mglShaderSource(ctx, shader, count, strings, NULL);
	mglCompileShader(ctx, shader);
	
	GLuint program = mglCreateProgram(ctx);
	if (!program) {
		mglDeleteShader(ctx, shader);
		return 0;
	}
	
	mglAttachShader(ctx, program, shader);
	mglLinkProgram(ctx, program);
	mglDeleteShader(ctx, shader);
	
	return program;
}

void mglCreateTransformFeedbacks(GLMContext ctx, GLsizei n, GLuint *ids)
{
	for (GLsizei i = 0; i < n; i++)
	{
		mglGenTransformFeedbacks(ctx, 1, &ids[i]);
	}
}





void mglDeleteTransformFeedbacks(GLMContext ctx, GLsizei n, const GLuint *ids)
{
    for (GLsizei i = 0; i < n; i++)
    {
        if (ids[i] == 0)
            continue;
            
        TransformFeedback *ptr = findTransformFeedback(ctx, ids[i]);
        if (!ptr)
            continue;
            
        // Can't delete if active
        if (ptr->active)
        {
            STATE(error) = GL_INVALID_OPERATION;
            continue;
        }
            
        // If deleting currently bound transform feedback, unbind it
        if (STATE(transform_feedback) && STATE(transform_feedback)->name == ids[i])
        {
            STATE(transform_feedback) = NULL;
        }
        
        // Remove from hash table and free
        deleteHashElement(&STATE(transform_feedback_table), ids[i]);
        free(ptr);
    }
}



void mglDepthRangef(GLMContext ctx, GLfloat n, GLfloat f)
{
	mglDepthRange(ctx, (GLdouble)n, (GLdouble)f);
}








void mglEndTransformFeedback(GLMContext ctx)
{
	if (!STATE(transform_feedback) || !STATE(transform_feedback)->active)
	{
		STATE(error) = GL_INVALID_OPERATION;
		return;
	}

	STATE(transform_feedback)->active = GL_FALSE;
	STATE(transform_feedback)->paused = GL_FALSE;
}


void mglGenTransformFeedbacks(GLMContext ctx, GLsizei n, GLuint *ids)
{
    for (GLsizei i = 0; i < n; i++)
    {
        ids[i] = getNewName(&STATE(transform_feedback_table));
        getTransformFeedback(ctx, ids[i]);
    }
}


void mglGetActiveSubroutineName(GLMContext ctx, GLuint program, GLenum shadertype, GLuint index, GLsizei bufSize, GLsizei *length, GLchar *name)
{
	// Subroutines - return empty string
	(void)program; (void)shadertype; (void)index; (void)bufSize;
	if (length) *length = 0;
	if (name && bufSize > 0) name[0] = '\0';
}












void mglGetMultisamplefv(GLMContext ctx, GLenum pname, GLuint index, GLfloat *val)
{
	// Get sample positions for multisample rendering
	if (pname != GL_SAMPLE_POSITION) {
		STATE(error) = GL_INVALID_ENUM;
		return;
	}
	
	// Metal uses fixed sample positions based on sample count
	// Return reasonable default positions (center for simplicity)
	val[0] = 0.5f;
	val[1] = 0.5f;
}

void mglGetObjectLabel(GLMContext ctx, GLenum identifier, GLuint name, GLsizei bufSize, GLsizei *length, GLchar *label)
{
	// No labels stored
	(void)identifier;
	(void)name;
	if (length) *length = 0;
	if (label && bufSize > 0) label[0] = '\0';
}

void mglGetObjectPtrLabel(GLMContext ctx, const void *ptr, GLsizei bufSize, GLsizei *length, GLchar *label)
{
	// No labels stored
	(void)ptr;
	if (length) *length = 0;
	if (label && bufSize > 0) label[0] = '\0';
}



void mglGetProgramPipelineInfoLog(GLMContext ctx, GLuint pipeline, GLsizei bufSize, GLsizei *length, GLchar *infoLog)
{
	// Pipeline info log - return empty
	(void)pipeline;
	if (length) *length = 0;
	if (infoLog && bufSize > 0) infoLog[0] = '\0';
}



GLint  mglGetProgramResourceLocation(GLMContext ctx, GLuint program, GLenum programInterface, const GLchar *name)
{
	// Program resource location - return -1 (not found)
	(void)program; (void)programInterface; (void)name;
	return -1;
}

GLint  mglGetProgramResourceLocationIndex(GLMContext ctx, GLuint program, GLenum programInterface, const GLchar *name)
{
	// Program resource location index - return -1 (not found)
	(void)program; (void)programInterface; (void)name;
	return -1;
}














void mglGetShaderPrecisionFormat(GLMContext ctx, GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision)
{
	// Return shader precision format - full precision for all types
	(void)shadertype;
	(void)precisiontype;
	if (range) {
		range[0] = 127;
		range[1] = 127;
	}
	if (precision) {
		*precision = 23;
	}
}












void mglGetnMapdv(GLMContext ctx, GLenum target, GLenum query, GLsizei bufSize, GLdouble *v)
{
	// TODO: Implement
	(void)ctx;
}

void mglGetnMapfv(GLMContext ctx, GLenum target, GLenum query, GLsizei bufSize, GLfloat *v)
{
	// TODO: Implement
	(void)ctx;
}

void mglGetnMapiv(GLMContext ctx, GLenum target, GLenum query, GLsizei bufSize, GLint *v)
{
	// TODO: Implement
	(void)ctx;
}

void mglGetnPixelMapfv(GLMContext ctx, GLenum map, GLsizei bufSize, GLfloat *values)
{
	// TODO: Implement
	(void)ctx;
}

void mglGetnPixelMapuiv(GLMContext ctx, GLenum map, GLsizei bufSize, GLuint *values)
{
	// TODO: Implement
	(void)ctx;
}

void mglGetnPixelMapusv(GLMContext ctx, GLenum map, GLsizei bufSize, GLushort *values)
{
	// TODO: Implement
	(void)ctx;
}







GLboolean mglIsTransformFeedback(GLMContext ctx, GLuint id)
{
	TransformFeedback *ptr = findTransformFeedback(ctx, id);
	return ptr ? GL_TRUE : GL_FALSE;
}




void mglNormalP3ui(GLMContext ctx, GLenum type, GLuint coords)
{
	// TODO: Implement
	(void)ctx;
}

void mglNormalP3uiv(GLMContext ctx, GLenum type, const GLuint *coords)
{
	// TODO: Implement
	(void)ctx;
}





void mglPauseTransformFeedback(GLMContext ctx)
{
	if (!STATE(transform_feedback) || !STATE(transform_feedback)->active || STATE(transform_feedback)->paused)
	{
		STATE(error) = GL_INVALID_OPERATION;
		return;
	}

	STATE(transform_feedback)->paused = GL_TRUE;
}
























































void mglProvokingVertex(GLMContext ctx, GLenum mode)
{
	// Set provoking vertex mode - no-op
	if (mode != GL_FIRST_VERTEX_CONVENTION && mode != GL_LAST_VERTEX_CONVENTION) {
		STATE(error) = GL_INVALID_ENUM;
		return;
	}
	// State not tracked
}





void mglResumeTransformFeedback(GLMContext ctx)
{
	if (!STATE(transform_feedback) || !STATE(transform_feedback)->active || !STATE(transform_feedback)->paused)
	{
		STATE(error) = GL_INVALID_OPERATION;
		return;
	}

	STATE(transform_feedback)->paused = GL_FALSE;
}





void mglSecondaryColorP3ui(GLMContext ctx, GLenum type, GLuint color)
{
	// TODO: Implement
	(void)ctx;
}

void mglSecondaryColorP3uiv(GLMContext ctx, GLenum type, const GLuint *color)
{
	// TODO: Implement
	(void)ctx;
}




// TexBuffer moved to texture_buffer.c

// TexBufferRange moved to texture_buffer.c

// TexStorage2DMultisample moved to texture_multisample.c

// TexStorage3DMultisample moved to texture_multisample.c















































































void mglVertexP2ui(GLMContext ctx, GLenum type, GLuint value)
{
	// TODO: Implement
	(void)ctx;
}

void mglVertexP2uiv(GLMContext ctx, GLenum type, const GLuint *value)
{
	// TODO: Implement
	(void)ctx;
}

void mglVertexP3ui(GLMContext ctx, GLenum type, GLuint value)
{
	// TODO: Implement
	(void)ctx;
}

void mglVertexP3uiv(GLMContext ctx, GLenum type, const GLuint *value)
{
	// TODO: Implement
	(void)ctx;
}

void mglVertexP4ui(GLMContext ctx, GLenum type, GLuint value)
{
	// TODO: Implement
	(void)ctx;
}

void mglVertexP4uiv(GLMContext ctx, GLenum type, const GLuint *value)
{
	// TODO: Implement
	(void)ctx;
}




#ifdef MGL_GL_ES
void  mglBlendBarrier(GLMContext ctx)
{
    // Metal already orders fragment writes to the same pixel
}

void mglPrimitiveBoundingBox(GLMContext ctx, GLfloat minX, GLfloat minY, GLfloat minZ, GLfloat minW, GLfloat maxX, GLfloat maxY, GLfloat maxZ, GLfloat maxW)
{
    
}
#endif
